version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin 
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - docker build -t danieliver/node-simple-chat .
  post_build:
    commands:
      - docker push danieliver/node-simple-chat